name: scrape
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pup
        run: | 
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip
      - name: Scrape table
        run: |
          curl https://cdm.unfccc.int/Registry/vcnotices |
            ./pup '#registry table' > asks.html
          curl https://cdm.unfccc.int/Registry/vcnotices/eois_list |
            ./pup '#registry table' > bids.html
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add asks.html bids.html
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
