name: scrape
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.14'
          check-latest: true
      - name: Install pup
        run: go install github.com/ericchiang/pup
      - name: Scrape table
        run: |
          curl https://cdm.unfccc.int/Registry/vcnotices/eois_list |
            pup '#registry table' > table.html
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
